export const Icons = {
    "Argent" : "money",
    "Argent sale" : "money",
    "Saumon" : "saumon",
    "Carabine" : "ar",
    "Cannabis" : "weed",
    "Canne à pêche" : "rod",
    "Lance-grenades compact" : "lancegrenade",
    "Hamburger" : "burger",
    "Pistolet cal.50" : "pistol",
    "Kebab" : "kebab",
    "Saumon frais" : "saumon",
    "Donut" : "donut",
    "Pinces" : "pinces",
    "Lampe torche" : "flashlight",
    "Pistolet vintage" : "pistol",
    "Canette vide" : "can",
    "Terre" : "dirt",
    "Terre humide" : "dirt",
    "Truite bull" : "truite",
    "Mallette métal" : "suitcase",
    "Spatules" : "saumon",
    "Mallette" : "suitcase",
    "Queue de billard" : "billardqueue",
    "Pistolet extra-terrestre" : "smg",
    "Sulfateuse Gusenberg" : "smg",
    "Calibre 12" : "bullet",
    "Bourbon" : "alcool",
    "Jus de carotte" : "drink",
    "Outil de crochetage" : "lockpick",
    "Grosse caméra" : "camera",
    "Fusil bullpup" : "ar",
    "Magnum" : "alcool",
    "Carte d'identité" : "passport",
    "Fusil de précision lourd" : "sniper",
    "Vélo" : "bicycle",
    "Permis" : "driverlicense",
    "ADP de combat" : "smg",
    "TEC-9" : "smg",
    "Tee-shirt" : "shirt",
    "Bouteille" : "alcool",
    "Dague" : "dague",
    "Sac poubelle" : "trashbag",
    "Matraque" : "nightstick",
    "Revolver classique" : "revolver",
    "Fusil à pompe d'assaut" : "shotgun",
    ".45 ACP" : "bullet",
    "Truite de lac" : "saumon",
    "JVN" : "binoculars",
    "Saumon cru" : "saumon",
    "Perche rock" : "saumon",
    "Hache de guerre" : "waraxe",
    "Grande bouche" : "saumon",
    "Grenade" : "grenade",
    "Sawed off" : "shotgun",
    "Coca" : "seed",
    "Opium" : "seed",
    "Crabe" : "meal",
    "Jumelles" : "binoculars",
    "Katana" : "katana",
    "Pistolet lourd" : "pistol",
    "Chinook" : "saumon",
    "Gardon" : "saumon",
    "Huître" : "huitre",
    "Fusil à pompe lourd" : "shotgun",
    "Gaz lacrymogène" : "gas",
    "Pépite d'or" : "goldnugget",
    "Mitrailleuse de combat" : "smg",
    "Bière" : "beer",
    "Cran d'arrêt" : "switchblade",
    "Tenue" : "outfit",
    ".300 Magnum" : "bullet",
    "L'américain" : "burger",
    "Bidon d'essence" : "jerrycan",
    "Jeton" : "chips",
    "Chocolat" : "chocolate",
    "Whisky" : "alcool",
    "Thé vert" : "drink",
    "Graîne de cannabis" : "seed",
    "Perche micro" : "micro",
    "Boîtier de piratage" : "phone",
    "Radio" : "radio",
    "Mitraillette d'assaut" : "smg",
    "Pistolet de combat" : "pistol",
    "Tenue EMS" : "ems",
    "Zip Ties" : "cuff",
    "Fusil d'assaut" : "ar",
    "Tenue BCSO" : "bcso",
    "Truite arc-en-ciel" : "truite",
    "Chanvre" : "chanvre2",
    "Chanvre traité" : "chanvre",
    "Tenue LSPD" : "lspd",
    "Tenue LCPD" : "lcpd",
    "Fusil à pompe" : "shotgun",
    "Nokia piratage" : "phone",
    "Kit de lavage" : "clean",
    "Bombe collante" : "grenade",
    "Trousse de soin" : "healthkit",
    "Chaise roulante" : "wheelchair",
    "Machette" : "machette",
    "Bière sans alcool" : "beer",
    "Pied de biche" : "crowbar",
    "Uranium brut" : "uranium",
    "Hachette" : "waraxe",
    "Téléphone" : "phone",
    "Eau de source" : "waterbottle",
    "Trousse à outils" : "toolbox",
    "Pistolet" : "pistol",
    "Micro CNN" : "micro",
    "Engrais" : "engrais",
    "Soda" : "can",
    "Fusil de précision" : "sniper",
    "Bois usé" : "wood",
    "Fusil amélioré" : "ar",
    "Gants de boxe" : "gloves",
    "Vêtement" : "shirt",
    "Fricadelle" : "meal",
    "Champagne" : "alcool",
    "Parachute" : "parachute",
    "Lance-missiles" : "ar",
    "Cigarette" : "malboro",
    "Cartouche" : "bullet",
    "Oreillette" : "radio",
    "Poing américain" : "knuckle",
    "Perceuse" : "drill",
    "Extincteur" : "extincteur",
    "Tortue dépecée" : "turtle",
    "Roue de secours" : "wheel",
    "Mitraillette légère" : "smg",
    "Graîne" : "seed",
    "Bombe artisanale" : "grenade",
    "Sac" : "bag",
    "Raisin" : "raisin",
    "Batte de baseball" : "bat",
    "Acier" : "steel",
    "Chips" : "chips2",
    "9mm" : "bullet",
    "Uranium" : "uranium2",
    "Mine de proximité" : "grenade",
    "Tequila" : "alcool",
    "Cocktail" : "alcool",
    "Tender" : "meal",
    "Pistolet mitrailleur" : "smg",
    "Cocaïne" : "cocaine",
    "Héroïne" : "cocaine",
    "Moteur" : "engine",
    "Carte bancaire" : "cb",
    "Méthamphétamine" : "meth",
    "Jupiler" : "beer",
    "Mitrailleuse" : "ar",
    "Marteau" : "hammer",
    "Boîte de munitions" : "ammo",
    "Lait de soja" : "milk",
    "Acier brut" : "iron",
    "Coktail molotov" : "molotov",
    "Triple bière" : "beer",
    "Surf" : "surf",
    "Fusil à pompe bullpup" : "ar",
    "Menottes" : "cuff",
    "Mégaphone" : "megaphone",
    "Boîtier darknet" : "phone",
    "Liqueur de Striker" : "clean",
    "5.56mm" : "bullet",
    "GPS" : "gps",
    "Casserole" : "saucepan",
    "Ch'ti burger" : "burger",
    "Hot-dog" : "hotdog",
    "Blé" : "wheat",
    "Fusil de précision à lunette" : "sniper",
    "Pain" : "bread",
    "Kokanee" : "saumon",
    "Bloc-note" : "notepad",
    "Plaque d'immatriculation" : "plate",
    "Vin" : "alcool",
    "Accessoire" : "tie",
    "Meuble" : "meuble",
    "Bombe de peinture" : "paintspray",
    "Ciseaux" : "ciseaux",
    "Fusil compact" : "ar",
    "Taser" : "taser",
    "Ombre de l'arctique" : "saumon",
    "Kevlar" : "kevlar",
    "Bouteille vide" : "waterbottle",
    "Masque" : "mask",
    "Clé anglaise" : "wrench",
    "Pétoire" : "pistol",
    "Pioche" : "pickaxe",
    "Masse" : "sledgehammer",
    "Pelle" : "shovel",
    "Esturgeon pâle" : "saumon",
    "Musquet" : "ar",
    "7.62mm" : "bullet",
    "Balle de baseball" : "bat",
    "Club de golf" : "golfclub",
    "Bouteille cassée" : "bottlewep",
    "Frites" : "meal",
    "Cyanure" : "pill",
    "Revolver" : "revolver",
    "Café" : "coffee",
    "Vodka" : "alcool",
    "Pistolet de détresse" : "flaregun",
    "Mitraillette" : "smg",
    "Fusil à impulsion" : "ar",
    "Fusil à double canon" : "shotgun",
    "Couteau" : "knife",
    "Parapluie" : "umbrella",
    "Tapas" : "meal",
    "Carabine spéciale" : "ar",
    "Petite bouche" : "saumon",
    "Viande crue" : "meat",
    "Lapin cru" : "meat",
    "Lion cru" : "meat",
    "Viande de chien" : "meat",
    "Viande de chat" : "meat",
    "Poisson rare" : "saumon",
    "Plume rare" : "feather",
    "Phosphore rouge" : "redp",
    "Acide sulfurique" : "acid",
    "Méthylamine" : "barrel",

    "Fer brut" : "iron_ingot",
    "Metal brut" : "iron",
    "Metal" : "metal_ingot",
    "Outil en fer" : "tool",
    "Composant électronique" : "techtrash",
    "Carte mère" : "motherboard",
    "Caoutchouc" : "caoutchouc",
    "Outil en caoutchouc" : "caoutchouc",
    "Outil en acier" : "tool",
    "Outil en metal" : "tool",
    "Sodium" : "sodium",
    "Solution chimique" : "acid",
    "Papier à rouler" : "rouler",
    "Tabac" : "tabac",
    "Pièce de tissu" : "cloth",
    "Farine" : "cocaine",
    "Alcool" : "alcool",
    "Verre" : "glass",
    "Légume" : "carrot",
    "Plat préparé" : "meal",
    "Sel" : "cocaine",
    "Viande préparée" : "meat",
    "Outil en bois" : "tool",
    "Bois" : "wood"
}